Update left turn approaches
avenueconsultants/ATSPM pull request #45
Opened 2022-07-26 23:20 UTC by avetraffic

-Fix ped delay so that ped recall is not displayed if no red-to-red cycles are found
-Fix signal data check report to not break if there is an error in the backend and no view models are created.
-Fix left turn gap to use correct signal and approach versions if checking older data.

The signal repo change I mentioned is the Signal  GetVersionOfSignalByDate method. 
I've updated it to include the AddSignalAndDetectorLists needed to find the left turns.
I don't think adding it should create any issues, and I've tested all the metrics to make sure they still work after changing it. We can extract it into it's own method though if you prefer.

2022-07-29 02:56 UTC, dloweAvenueConsultants requested changes
1. If I am not mistaken you change to the Signal.cs file will never evaluate as empty or null.
2. Why are you using the view bag in the LeftTurnGapController. If possible we should add it to the view model.

2022-07-29 03:41 UTC, avetraffic commented
1. I ran a non-signal number through it and it returned null for me.
2. You're right, that's probably not the best way. The issue is that instead of returning "check detectors" or something similar, it now breaks if they choose a signal and date with no data. Do you remember why we added the "if (signalDataCheckReportViewModel != null)" before saving the viewModel to the list? It used to work before that, but now we're not guaranteed any viewModels.

2022-08-04 15:14 UTC, avetraffic commented
Additional changes:
-Fix error in Approach Volume Chart
-Update about page

2022-08-07 21:30 UTC, dloweAvenueConsultants approved these changes
Looks Good!

2022-08-07 21:30 UTC, merged